export default {
	LOGGED_IN: "LOGGED_IN",
	USER_SIGNED_UP: "USER_SIGNED_UP",
	USER_FETCHED: "USER_FETCHED",
	USERS_FETCHED: "USERS_FETCHED",
	USER_ADDED_TO_CONTACTLIST: "USER_ADDED_TO_CONTACTLIST",
	CONTACTS_FETCHED: "CONTACTS_FETCHED"
}