export default {
	//AUTH REDUCER
	LOGGED_IN: "LOGGED_IN",
	USER_SIGNED_UP: "USER_SIGNED_UP",
	//USER REDUCER
	USER_FETCHED: "USER_FETCHED",
	USERS_FETCHED: "USERS_FETCHED",
	USER_ADDED_TO_CONTACTLIST: "USER_ADDED_TO_CONTACTLIST",
	CONTACTS_FETCHED: "CONTACTS_FETCHED",
	//CHAT REDUCER
	CONTACT_CHAT_FETCHED: "CONTACT_CHAT_FETCHED",
	NEW_CHAT_OPENED: "NEW_CHAT_OPENED",
	CHAT_CLOSED: "CHAT_CLOSED",
	CHAT_ACTIVATED: "CHAT_ACTIVATED",
	ACTIVE_CHAT_FETCHED: "ACTIVE_CHAT_FETCHED",
	//MESSAGE REDUCER: 
	MESSAGE_SENT: "MESSAGE_SENT",
	MESSAGES_FETCHED: "MESSAGES_FETCHED",
	//RESET REDUX STATE
	LOGGED_OUT: "LOGGED_OUT"
}