export default {
	//AUTH REDUCER
	LOGGED_IN: "LOGGED_IN",
	USER_SIGNED_UP: "USER_SIGNED_UP",
	//USER REDUCER
	CURRENT_USER_FETCHED: "CURRENT_USER_FETCHED",
	USER_FETCHED: "USER_FETCHED",
	USERS_FETCHED: "USERS_FETCHED",
	USER_ADDED_TO_CONTACTLIST: "USER_ADDED_TO_CONTACTLIST",
	CONTACTS_FETCHED: "CONTACTS_FETCHED",
	ACTIVE_CONTACT_FETCHED: "ACTIVE_CONTACT_FETCHED",
	CONTACT_ACTIVATED: "CONTACT_ACTIVATED",
	//CHAT REDUCER
 	CHATS_FETCHED:  "CHATS_FETCHED",
	NEW_CHAT_OPENED: "NEW_CHAT_OPENED",
	CHAT_CLOSED: "CHAT_CLOSED",
	CHAT_ACTIVATED: "CHAT_ACTIVATED",
	ACTIVE_CHAT_SET: "ACTIVE_CHAT_SET",
	ACTIVE_CHAT_FETCHED: "ACTIVE_CHAT_FETCHED",
	//MESSAGE REDUCER: 
	MESSAGE_SENT: "MESSAGE_SENT",
	MESSAGES_FETCHED: "MESSAGES_FETCHED",
	MESSAGES_FETCHED_FROM_ACTIVE: "MESSAGES_FETCHED_FROM_ACTIVE",
	//RESET REDUX STATE
	LOGGED_OUT: "LOGGED_OUT"
}